In [ ]:
import numpy as np
import random
from timeit import timeit
def add_python(Z1,Z2):
  return [z1+z2 for z1,z2 in zip(Z1,Z2)]
def add_numpy(Z1,Z2):
  return np.add(Z1,Z2)
Z1 = random.sample(range(1000),100)
Z2 = random.sample(range(1000),100)
python_time = timeit("add_python(Z1,Z2)", globals=globals(),number=1000)
numpy_time = timeit("add_numpy(Z1,Z2)", globals=globals(),number=1000)
print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"NumPy addition: {numpy_time:.2f} s per loop")


Pure Python addition: 0.02 s per loop
NumPy addition: 0.03 s per loop


In [ ]:
import numpy as np
import random
from timeit import timeit
def add_python(Z1,Z2):
  return [z1+z2 for z1,z2 in zip(Z1,Z2)]
def add_numpy(Z1,Z2):
  return np.add(Z1,Z2)
size = 1000
Z1_list = random.sample(range(size+1),size)
Z2_list = random.sample(range(size+1),size)
Z1_np = np.array(Z1_list)
Z2_np = np.array(Z2_list)
python_time = timeit("add_python(Z1_list, Z2_list)", globals=globals(),number=100)
numpy_time = timeit("add_numpy(Z1_np, Z2_np)", globals=globals(),number=100)
print(f"Pure Python addition: {python_time:.6f} seconds per loop")
print(f"Numpy addition: {numpy_time:.6f} seconds per loop")

Pure Python addition: 0.009343 seconds per loop
Numpy addition: 0.000189 seconds per loop


In [ ]:
array_0d = np.array(5)
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])
for i,arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
  print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")




0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
Shape: (1, 4, 2)



In [ ]:
array = np.array([[1,2,3],[4,5,6]])
reshaped_array = array.reshape(3,2)
print("Original Shape:",array.shape,"\nReshaped Shape:", reshaped_array.shape)


Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [ ]:
a = np.arange(1,10)
print(a)
x = range(1,10)
print(x)
print(list(x))
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
print(np.linspace(1,10)) #if nothing mention 50 is default value
print(np.linspace(1,10,7))
print(np.linspace(1,10,7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [ ]:
ones_array = np.ones((2,3))
zeros_array = np.zeros((3,2))
empty_array = np.empty((2,2))
identity_matrix = np.eye(3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')


[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.89374922e-310 0.00000000e+000]
 [6.52389539e-310 6.52389532e-310]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
array_from_list = np.array ([1 , 2 , 3]) # [1 2 3]
array_from_tuple = np.array ((4 , 5 , 6) ) # [4 5 6]
array_from_nested_list = np.array ([[1 , 2 , 3] , [4 , 5 ,6]]) # [[1 2 3] [4 5 6]]
print(array_from_list , array_from_tuple ,array_from_nested_list , sep ='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
# Creating Array with Shape of existing array :
zeros , ones , empty = np.zeros(arr.shape) , np.ones(arr.shape),np.empty( arr.shape )
print(arr,zeros,ones,empty,sep ='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [ ]:
array = np.array([1,2,3])
new_array = array*2
copied_array = np.copy(array)
sliced_array = array[1:2]
print(new_array,copied_array,sliced_array)

[2 4 6] [1 2 3] [2]


In [ ]:
arr1 = np.array([[1,2],[2,3]])
arr2 = np.array([[5,6],[7,8]])
hstacked = np.hstack((arr1,arr2))
vstacked = np.vstack((arr1,arr2))
colstacked = np.column_stack((arr1[0], arr2[0])) #column ma arrange hunxa
print(hstacked, vstacked, colstacked, sep='\n')

[[1 2 5 6]
 [2 3 7 8]]
[[1 2]
 [2 3]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
concat_axis0 = np.concatenate((arr1,arr2), axis=0)
concat_axis1 = np.concatenate((arr1,arr2), axis=1)
print(concat_axis0,"\n",concat_axis1,sep='\n')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1d = np.array([0,1,2,3,4,5])
arr2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr3d = np.array([[[0 , 1] , [2 , 3]] , [[4 , 5] , [6 , 7]] , [[8 ,9] , [10 , 11]]])
print("Basic :", arr1d [1:4] , arr2d [1:3 , 0:2] , arr3d [1:2 , 0:2 ,1:2])
print (" Step :", arr1d [1:5:2] , arr2d [::2 , 1::2] , arr3d [::2 ,::2 , 1::2])


Basic : [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
 Step : [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Add:", np.add(arr1, arr2))
print("Subtract:", np.subtract(arr1, arr2))
print("Divide:", np.divide(arr1, arr2))
print("Multiply:", np.multiply(arr1, arr2))
print("Power:", np.power(arr1, arr2))
print("Exp:", np.exp(arr1))


Add: [5 7 9]
Subtract: [-3 -3 -3]
Divide: [0.25 0.4  0.5 ]
Multiply: [ 4 10 18]
Power: [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
result_dot = np.dot(A,B)
print (" Result with np.dot :\n", result_dot )


 Result with np.dot :
 [[ 58  64]
 [139 154]]


In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
result_at = A@B
print(" Result with @ operator :\n", result_at)
result_matmul = np . matmul (A , B )
print(" Result with np. matmul :\n", result_matmul)


 Result with @ operator :
 [[ 58  64]
 [139 154]]
 Result with np. matmul :
 [[ 58  64]
 [139 154]]


In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse :\n", np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
print("2-Norm (Euclidean):", np.linalg.norm(A))
print("Solution x:", np.linalg.solve(A, B))


Inverse :
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]
