Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
empty_arr = np.empty((2,2)) #1
ones_arr = np.ones((4,2))#2
#3
fill_value_arr = np.full((3, 3), 7)
print("\nArray filled with 7 (3x3):\n", fill_value_arr)
#4
given_arr = np.array([[1, 2], [6, 9]])
zeros_like_arr = np.zeros_like(given_arr)
print("\nArray of zeros with same shape as given array:\n", zeros_like_arr)
#5
ones_like_arr = np.ones_like(given_arr)
print("\nArray of ones with same shape as given array:\n", ones_like_arr)
#6
new_list = [1, 2, 3, 4]
numpy_arr = np.array(new_list)
print("\nConverted NumPy array from list:\n", numpy_arr)


Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of zeros with same shape as given array:
 [[0 0]
 [0 0]]

Array of ones with same shape as given array:
 [[1 1]
 [1 1]]

Converted NumPy array from list:
 [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
arr = np.array(range(10,50))
print("Array with values ranging from 10 to 49:\n", arr)
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values ranging from 0 to 8:\n", matrix_3x3)
identity_arr = np.eye(3,3)
print(identity_arr)
# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array (size 30):\n", random_array)
print("Mean of the array:", mean_value)
# 5. Create a 10x10 array with random values and find min and max
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\n10x10 Array with random values:\n", random_matrix)
print("Minimum value:", min_value)
print("Maximum value:", max_value)
# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 is the 5th element
print("\nZero array with 5th element replaced by 1:\n", zero_array)
# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\nReversed array:\n", reversed_array)
# 8. Create a 2d array with 1 on border and 0 inside.
one_border = np.ones((5,5))
one_border[1:-1, 1:-1] = 0
print("\n2D Array with 1 on the border and 0 inside:\n", one_border)


Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array (size 30):
 [0.44440899 0.02724456 0.82732545 0.17412967 0.65876237 0.73496906
 0.20140329 0.61319197 0.33166989 0.54387511 0.01459075 0.40882891
 0.90650994 0.84031847 0.82957359 0.39557772 0.86824045 0.1768436
 0.2394696  0.91975974 0.49956037 0.30246164 0.95279806 0.94516377
 0.27516486 0.62009265 0.86809185 0.75065902 0.37125306 0.79830299]
Mean of the array: 0.5513413789220867

10x10 Array with random values:
 [[0.38539806 0.94002161 0.10679964 0.59531861 0.34185756 0.9995365
  0.32367558 0.41729449 0.50725499 0.93228416]
 [0.42299107 0.72670028 0.46801557 0.78186137 0.30370196 0.1519069
  0.93412189 0.56847884 0.61501275 0.08876232]
 [0.99734763 0.16389317 0.23725166 0.12717674 0.87196619 0.71880

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays using np.add()
addition = np.add(x, y)
print("Addition of x and y:\n", addition)

# 2. Subtract the two arrays using np.subtract()
subtraction = np.subtract(x, y)
print("\nSubtraction of x and y:\n", subtraction)

# 3. Multiply the arrays by integers using np.multiply()
multiplication_x = np.multiply(x, 3)  # Multiply x by 3
multiplication_y = np.multiply(y, 2)  # Multiply y by 2
print("\nMultiplication of x by 3:\n", multiplication_x)
print("Multiplication of y by 2:\n", multiplication_y)

# 4. Find the square of each element using np.square()
square_x = np.square(x)
square_y = np.square(y)
print("\nSquare of elements in x:\n", square_x)
print("Square of elements in y:\n", square_y)

# 5. Compute dot products using np.dot()
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y
print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along rows using np.concatenate() and v and w along columns using np.vstack()
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_column = np.vstack((v, w)).T  # Transpose for column-wise concatenation
print("\nConcatenation of x and y along rows:\n", concat_xy_row)
print("Concatenation of v and w along columns:\n", concat_vw_column)

# 7. Attempt to concatenate x and v using np.concatenate() (observe the error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]
Multiplication of y by 2:
 [[10 12]
 [14 16]]

Square of elements in x:
 [[ 1  4]
 [ 9 25]]
Square of elements in y:
 [[25 36]
 [49 64]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}


In [ ]:
import numpy as np

# Matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

### 1. Prove A.A⁻¹ = I (Identity Matrix)
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("1. A * A⁻¹:\n", identity)  # Should result in Identity matrix

### 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB == BA:", np.array_equal(AB, BA))

### 3. Prove (AB)ᵀ = BᵀAᵀ
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)  # BᵀAᵀ
print("\n3. (AB)ᵀ:\n", AB_transpose)
print("BᵀAᵀ:\n", BT_AT)
print("(AB)ᵀ == BᵀAᵀ:", np.array_equal(AB_transpose, BT_AT))

# Represent the system in Matrix form: AX = B
A_eq = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])
B_eq = np.array([-1, -3, 9])

# Solve using np.linalg.inv
A_eq_inv = np.linalg.inv(A_eq)  # Find the inverse of A
X = np.dot(A_eq_inv, B_eq)  # Solve for X using X = A⁻¹B
print("\nSolution using Inverse Method:\n", X)

# Alternatively, solve using np.linalg.solve (numerically more stable)
X_solve = np.linalg.solve(A_eq, B_eq)
print("\nSolution using np.linalg.solve:\n", X_solve)


In [ ]:
import time
import numpy as np

# 1. Element-wise Addition
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.arange(size)
array2 = np.arange(size)

# Python Lists Addition
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
time_list_addition = time.time() - start_time
print("Time taken for element-wise addition (Python lists):", time_list_addition, "seconds")

# NumPy Arrays Addition
start_time = time.time()
result_array = array1 + array2
time_numpy_addition = time.time() - start_time
print("Time taken for element-wise addition (NumPy arrays):", time_numpy_addition, "seconds")

# 2. Element-wise Multiplication
# Python Lists Multiplication
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
time_list_multiplication = time.time() - start_time
print("\nTime taken for element-wise multiplication (Python lists):", time_list_multiplication, "seconds")

# NumPy Arrays Multiplication
start_time = time.time()
result_array = array1 * array2
time_numpy_multiplication = time.time() - start_time
print("Time taken for element-wise multiplication (NumPy arrays):", time_numpy_multiplication, "seconds")

# 3. Dot Product
# Python Lists Dot Product
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
time_list_dot_product = time.time() - start_time
print("\nTime taken for dot product (Python lists):", time_list_dot_product, "seconds")

# NumPy Arrays Dot Product
start_time = time.time()
dot_product_array = np.dot(array1, array2)
time_numpy_dot_product = time.time() - start_time
print("Time taken for dot product (NumPy arrays):", time_numpy_dot_product, "seconds")

# 4. Matrix Multiplication
matrix_size = 1000
list_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
array_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
array_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

# Python Lists Matrix Multiplication
start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
time_list_matrix_mult = time.time() - start_time
print("\nTime taken for matrix multiplication (Python lists):", time_list_matrix_mult, "seconds")

# NumPy Arrays Matrix Multiplication
start_time = time.time()
result_matrix_numpy = np.dot(array_matrix1, array_matrix2)
time_numpy_matrix_mult = time.time() - start_time
print("Time taken for matrix multiplication (NumPy arrays):", time_numpy_matrix_mult, "seconds")


Time taken for element-wise addition (Python lists): 0.265488862991333 seconds
Time taken for element-wise addition (NumPy arrays): 0.005178213119506836 seconds

Time taken for element-wise multiplication (Python lists): 0.27299976348876953 seconds
Time taken for element-wise multiplication (NumPy arrays): 0.006001710891723633 seconds

Time taken for dot product (Python lists): 0.3046236038208008 seconds
Time taken for dot product (NumPy arrays): 0.002311229705810547 seconds

Time taken for matrix multiplication (Python lists): 203.36506867408752 seconds
Time taken for matrix multiplication (NumPy arrays): 1.2548246383666992 seconds
